### PR TITLE
Documentation and *stylin*

### PR DESCRIPTION
**Pull request by gambogi**
Added more documentation and gave commas room to breath

### CODE REVIEW

**Comment by TravisWhitaker** [comment]
Added documentation looks good.

However, with a few exceptions I think the "style" changes make the code at worst less clear and at best much uglier or wasteful of horizontal space.

In `main` in `dbInitMain.hs` the pattern match on the `getArgs` bind was changed to use the `[]` type-specific syntactic sugar rather than matching on the constructors directly. I think this makes what's going on much less clear, especially to someone who might not be aware that pattern matching on the LHS of named binds in do-notation is (somewhat uniquely) legal, or someone who might not have seen this (honestly quite lazy and in need of more semantic error reporting) specific pattern of simultaneous-argument-number-validation-and-name-binding before. If you think imperatively there's actually quite a lot going on in that single line, and explicitly using the constructors will at least throw a bone to those still on the list chapter of "Learn You A Haskell."

I'm even more confounded by the addition of almost one thousand extra spaces between the content and respective comma of each line of the one-line-per-item list literal style we're using. In my opinion, this style is already hideous looking, but the massive boost to programmatically editing the source is worth the offense to my delicate sensibilities. The addition of this extra space doesn't even serve to horizontally align the list contents with anything else. Indeed, in a few spots (19 in `dbInitMain.hs`; 19, 105, 128, 162, 179, 214, 265, 331, 458, 474, 491, 504, 528, 552, 562, 573, 584, 597, 609, 619, 630, 639, 651, 661, 672, 682, 692, and 728 in `Schema.hs` to be exhaustive) the first element of the list weirdly juts out from the four-column alignment that everything else obeys. These spaces don't help alignment (and sometimes hurt it), don't make the source more easily editable in an automated way, push things needlessly to the right, and overall look very unnatural to me. 

Finally, are we sure we want a freshman project to occupy a term? I guess there's no possibility for more than one major project per term, but it might be nice to store the date the project occurred, and that unambiguously places the project occurrence in a term. If we're going to use the `term` table for stuff other than dues I think that'll change the way we model that in the types a bit. If we definitely want to lean towards terms instead of dates, let's make all the requisite changes soon so the types reflect it.

**Comment by gambogi** [comment]
with regard to the `[]` pattern match, I just noticed it came up during hlint, and it made sense to me, but I have no problem with leaving the explicit constructors in. The first element jutting out is honestly just a mistake on my part when I was programmatically adding the spaces.
The case for keeping them out by enumerating the things that it doesn't do is not a strong one. @sdemos and myself (as well as presumably others but I won't speak for them) feel that the lack of looks worse.  This is purely a preference thing, but I would like us to standardize on it. The style that we are advocating is that used in `base`, so I feel it is much more common. See [Data.Data](https://hackage.haskell.org/package/base-4.8.0.0/docs/src/Data-Data.html#DataType)'s source for some examples. `Constr` is a good one. 

We also feel that `data` declarations should look like this:

```
data WhatAGreatType = YouKnowIt
                    |  Sister
```

as opposed to this:

```
data ImHardToEdit = Short            |
                    AbsurdlyLongName |
                    LongName
```

As we've noticed in some places of the code.

As for the freshman project thing, the change comes from two realizations:
- A freshman project could have multiple dates, and that relationship would be better expressed by linking the project to an event (which I just realized as I was typing this)
- There likely won't ever be more than one freshman project per year, let alone term, so it seems fine to break them up by term in this way.

**Comment by gambogi** [comment]
Accidentally closed.

**Comment by TravisWhitaker** [comment]
I would cringe just a bit less if the first element wasn't jutting out to the right.

Some style changes can bring "objective" benefits, e.g. making it easier to edit the source with macros. I'm trying to contrast this with changes that can be argued with something more than "This seems more common and looks nice."

`base` doesn't use a consistent style (although it is slowly but surely getting closer) and does a few other things that I find pretty ugly. For example, the `::` is always aligned with the equals sign in the first pattern of function definitions, which seems nice at first but begins to look ridiculous if the function has lots of arguments:

``` Haskell

f                                                   ::
f a b c d e g h i j k l m n o p q r s t u v q x y z =

```

You get the idea; `Control.Monad` and `Data.Monoid` are big offenders here. My point is that I'd hesitate to reference `base` as an example of good Haskell style. Imperfect analogy: no sane person would give `glibc` as an example of good C style just because it's the most common standard library for the language(unless you "feel that it is much more common" for some other reason); I take the style used in `base` with a similarly sized grain of salt.

There's not much I can do faced with a plurality of poor taste. If you insist on these insipid spaces, I suppose I have no choice but to force myself to write unnatural-seeming things, occasionally re-raising this point in the hope that the perpetrators will realize the error of their ways and apologize profusely for each time I'll be forced to gaze upon these list literal fecaliths anew, hairs standing on end, unpleasant frisson in full force.

I totally agree with the better-looking data declarations. The old style is a bad habit and I usually remember to do it the "right way" when I go back and individually document each constructor.

Ok, so will freshman projects be associated with an event, a term, or both? Although it may seem redundant, I think linking it to both retains the most information while simplifying the queries to generate things like the fall evals view.

**Comment by TravisWhitaker** [comment]
Damn, that's so easy to do accidentally.

**Comment by gambogi** [comment]
All set. Ready for merge

**Pull request merged**
