### PR TITLE
Breaking out the Frontend.hs file into bite-size chunks

### LINKED ISSUE #69: Investigate moving widgets and pages to their own files
I think it might be possible to break widgets and pages into separate files so that people who are added widgets and pages don't have to wade through all of the frontend haskell code to do what they want to do, and to make the project neater. 

In order to do this, I have to decompose mkYesod into it's component parts so that I can define different parts of the yesod site definition in different files, to solve the problem we are having with cyclic dependencies.

### PR DESCRIPTION
**Pull request by sdemos**
Fixes #69 

All new sections of the site should go in their own haskell file now. 

There is one question, do people think that all of the handler haskell files should go in their own folder under the `frontend` folder? I thought that the paths and modules names would be too long then, but if people think it would be too cluttered, I can change that and add it to this pr.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
I'm just gonna throw out that I really like this.

**Comment by sdemos** [comment]
Don't merge this until I update the documentation related to the frontend to reflect the new changes in frontend workflow. 
Still review it, though.

**Comment by sdemos** [comment]
Okay, documentation should be all set.

**Comment by sdemos** [comment]
Okay, documentation should be all set.

**Pull request merged**
