### PR TITLE
Sample page is done!

### PR DESCRIPTION
**Pull request by gambogi**
We have a decent looking topbar and background now!

### CODE REVIEW

**Comment by gambogi** [comment]
from this: 
screen shot 2015-06-11 at 4 45 33 pm

to this:
screen shot 2015-06-19 at 8 05 35 am

**Comment by harlanhaskins** [comment]
:+1:

**Comment by harlanhaskins** [comment]
Wonder if it should be centered and have a larger width...?

**Comment by gambogi** [comment]
That's deliberately off to the left, it's just an example panel

**Comment by sdemos** [comment]
Looks good to me.

**Comment by gambogi** [comment]
screen shot 2015-06-19 at 8 11 56 am

**Pull request merged**
