### PR TITLE
Define the Type Model

### PR DESCRIPTION
**Pull request by TravisWhitaker**
This needs a lot more documentation, but this will get people to start
thinking about the API. The 'Shadow' typeclass, the most non-obvious
part, is at least well documented.

### CODE REVIEW

**Comment by gambogi** [comment]
This all makes sense, but I think for application logic we would probably like to write that in a way that doesn't need to care about the shadowed state of the underlying model.

**Comment by TravisWhitaker** [comment]
We do want the application logic to be aware of shadowing, because we want every operation to encode exactly what must be unshadowed for it to be completed. The other options are forcing all of the structure(which is unacceptable for caching purposes) or lazy IO(which is unacceptable due to the transactional nature of the data); we can't guarantee repeatable reads without some sort of system like this.

**Comment by TravisWhitaker** [comment]
@harlanhaskins I think unpaid dues would be represented as a lack of a `Dues` record in the `memberDues` list for the `Term` of interest.

**Comment by TravisWhitaker** [comment]
@gambogi A third option would be literally representing relationships between structures with the database ID's alone, e.g. `memberEvaluations` would be of type `[Word64]`. I anticipate that this would clutter the application logic with lookups and force operations that would otherwise have the opportunity to be pure into the IO monad. `Shadowed` let's us push a lot of those checks for uninspected data into pattern matching, rather than having to inspect the cache.

**Comment by TravisWhitaker** [comment]
Ok, how would you guys feel about this:

``` haskell
data Member = Member {
    memberID            :: Word64
   ,memberUUID          :: UUID
   ,memberUsername      :: T.Text
   ,memberCommonname    :: T.Text
   ,memberToken         :: Maybe B.ByteString
   ,memberHousingPoints :: Int
   ,memberOnfloorStatus :: Bool
   ,memberEboards       :: Fetch [Eboard]
   ,memberRooms         :: Fetch [Room]
   ,memberMemberships   :: Fetch [Membership]
   ,memberEvaluations   :: Fetch [Evaluation]
   ,memberPackets       :: Fetch [Packet]
   ,memberQueues        :: Fetch [Queue]
   ,memberApplications  :: Fetch [Application]
   ,memberDues          :: Fetch [Dues]
   }
```

Where `Fetch` is a monad with a MonadIO instance. That way, if you have some pure function on the non-Fetchable components of a `Member`, you can do something like `pureMemberFunction <$> fetchMemberID 1337`. Pure functions on, say, `Member` and `[Eboard]`, and the current time could be something like:

``` haskell
do
    m <- fetchMemberID 1337
    e <- memberEboards m
    t <- liftIO posixTime
    return $ pureMemberEboardTimeFunction m e t
```

There will be some function like:

``` haskell
runFetch :: Pool Postgres -> LRU (TypeRep, Word64) Dynamic -> Fetch a -> IO a
```

Using generic programming to create a fair LRU of any type of cache-able object.

Thoughts?

**Comment by gambogi** [comment]
We've opted to pursue the fetch monad approach. Closing until that is addressed.

**Pull request closed without merging**
