### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by TravisWhitaker**
おねがいします。

### CODE REVIEW

**Comment by TravisWhitaker** [comment]
You can only have one open pull request per branch. Weird.

**Comment by eatnumber1** [comment]
The definition of a pull request is "please merge my branch into yours". What would it even mean to have multiple pull requests per branch?

**Comment by TravisWhitaker** [comment]
I was thinking it might be possible to have separate pull requests for groups of commits. It's probably better that you can't; this forces branches to represent small, specific changes.

**Comment by ryansb** [comment]
You can have a series of branches that make up a large change that make up a single lineage, so you can still have focused discussion on parts of a large change. 

Of course, at that point you'd be better of in a CL model like gerrit.

**Pull request merged**
